<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal">&times;</button>
	<h6 id="modal-formLabel"><i class="icon-group"></i>&nbsp;&nbsp;Add New Employee</h6>
</div>
<div class="modal-body">
	<p style="margin-left:10px;margin-top:10px;">* Required Fields</p>
	<?php echo $this->FormErrorHeader($this->form);?>
	<form id='<?php echo $this->form->getId();?>' action='<?php echo $this->form->getAction();?>' method='<?php echo $this->form->getMethod();?>' class="separate-sections form-horizontal fill-up">
		<?php echo $this->FormEl($this->form->firstname); ?>	
		<?php echo $this->FormEl($this->form->lastname); ?>	
	</form>
</div>
<div class="modal-footer">
	<button id="<?php echo $this->form->getId();?>_close" class="btn btn-default" data-dismiss="modal">Close</button>
	<button id="<?php echo $this->form->getId();?>_save" class="btn btn-blue" data-loading-text="Loading...">Save</button>
</div>
<script>
$('#<?php echo $this->form->getId();?>_save').click(function() {
	$(this).button('loading');			
	$.post('<?php echo $this->form->getAction();?>', 
			$('#<?php echo $this->form->getId();?>').serialize()
	)	
	.success(function(data, textStatus, jqXHR) {			
		$('#modal-form').html(data);
		if ($('#modal-form .alert-error').size() == 0) {
			$('#modal-form').modal('hide');
		    $('#content').load('/employee/index');
		    notification('New Employee has been successfully added.','success',3000);
	    }
	})
	.error(function() {
	});
});
</script>
