<div class="span10">	 
	<div class="box">
		<div class="box-content">
			<div id="dataTables">
				<table id='dTableEmployee'>  
					<thead> 
						<tr>
							<th>Action</th>								
							<th><div>Name</div></th>
							<th><div>Code</div></th>
						</tr>
					</thead>
					<tbody id='list'> 						
						<?php echo $this->partialLoop('employee/partial-row-employees.phtml',$this->employee);?>						
					 </tbody> 
				 </table>  
			</div>
		</div>
	</div>
</div>
<div id="modal-delete" class="modal fade" style="display: none";>
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal">&times;</button>
		<h6 id="modal-formLabel">
			<i class="icon-remove-sign"></i>&nbsp;&nbsp;Delete an Employee
		</h6>
	</div>
	<div class="modal-body">	
		<p>Are you sure you want to delete this Employee?</p>
	</div>
	<div class="modal-footer">
		<a class="btn btn-default" data-dismiss="modal">Cancel</a> 
		<a class="btn btn-blue " id="delete-modal-save">Delete</a>
	</div>
</div>
<script>
	updateEventEmployee();
</script>