<tr id='<?php echo $this->employee_id;?>'>
	<td class="center">
		<div class="btn-group">
			<a class=" btn-mini btn-default " data-toggle="dropdown"><i	class="icon-user"></i></a>
			<ul class="dropdown-menu">
				<li><a class='center remove' title='Delete/Remove'><i class="icon-remove-sign"></i>Delete/Remove</a></li>			
			</ul>
		</div>
	</td>
	<td class='center'><?php echo $this->emp_name;?></td>
	<td class='center'><?php echo $this->code;?></td>
</tr>