<link href="https://cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.1/bootstrap-editable/css/bootstrap-editable.css" media="screen" rel="stylesheet" type="text/css">
<link href="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css" media="screen" rel="stylesheet" type="text/css">
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.1/bootstrap-editable/js/bootstrap-editable.js"></script>
<script src="/javascripts/src/recovery/products.js"></script>
<div id="loader_image" style="text-align:center" >
  <img src="/images/blue_loading_3.gif" />
</div>
<div id="items-page" class="hidden" ng-non-bindable>
    <div class="box">
        <div class="box-content padded">
            <div class="tab-content">
                <div id="item-tab" style="padding: 5px">
                    <table id="itemTable" class="responsive"></table>                    
                </div>
            </div>
        </div>
    </div>
</div>